content_types:
  - name: "page"
    collection: false
  - name: "blog"
    collection: true
development:
  frontend: https://wwww.traaidmark.com
  data: 
    path: '../'
    content: '/content'
    assets: '/public'
  server:
    port: 4000
    cache: '../.cache'
    
