content_types:
  - name: "pages"
    collection: false
  - name: "articles"
    collection: 
      items: 2
development:
  frontend: https://wwww.traaidmark.com
  data: 
    path: '../data'
    content: '/content'
    assets: '/public'
  server:
    port: 4000
    cache: 
     path: '../.cache'
    log: 
      path: '../.logs'
    
